// Verifies the Content Credentials reader against a real signed record, a real
// unsigned file, and deliberately broken input.
//
// fixture-c2pa-chatgpt.png is a 1x1 PNG carrying the genuine, byte for byte
// caBX chunk from an image ChatGPT generated on 2026-09-19. The pixels are a
// stand in so the repo does not carry 2.4MB for one test; the provenance
// record under test is the real one, signed by OpenAI. The parser under test is the
// code extracted from index.html, so the test cannot drift from what ships.
import { readFileSync } from "node:fs";

const src = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const a = src.indexOf("  const IPTC_SOURCE = {");
const b = src.indexOf("  // =========================================================================\n  //  Perceptual hashing");
if (a < 0 || b < 0) { console.error("FAIL: could not extract the C2PA parser from index.html"); process.exit(1); }
const mod = await import("data:text/javascript," + encodeURIComponent(
  src.slice(a, b) + "\nexport { parseC2PA, findC2PABox };"
));

const buf = (p) => { const b = readFileSync(new URL(p, import.meta.url)); return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength); };
let fails = 0;
const check = (name, cond, got) => {
  if (cond) { console.log(`  PASS  ${name}`); }
  else { console.log(`  FAIL  ${name}  got: ${JSON.stringify(got)}`); fails++; }
};

// 1. a real ChatGPT PNG, signed by OpenAI
const ai = mod.parseC2PA(buf("./fixture-c2pa-chatgpt.png"));
check("signed PNG is detected",            ai !== null && ai.present === true, ai);
check("IPTC source type read",             ai && ai.sourceType === "trainedAlgorithmicMedia", ai && ai.sourceType);
check("source label mapped to plain words", ai && ai.sourceLabel === "generated by AI", ai && ai.sourceLabel);
check("software agent read",               ai && ai.software === "ChatGPT", ai && ai.software);
check("software version read",             ai && ai.version === "gpt-image", ai && ai.version);
check("claim generator read",              ai && ai.generator === "OpenAI Media Service API", ai && ai.generator);
check("watermark action seen",             ai && ai.watermarked === true, ai && ai.watermarked);
check("creation timestamp read",           ai && /^20\d\d-\d\d-\d\dT/.test(ai.created || ""), ai && ai.created);

// 2. an ordinary camera JPEG carries no record
check("unsigned JPEG returns null",        mod.parseC2PA(buf("../_base.jpg")) === null, "not null");

// 3. malformed and hostile input must return null, never throw or hang
const cases = {
  "empty buffer":        new Uint8Array(0),
  "one byte":            new Uint8Array([0x89]),
  "PNG header only":     new Uint8Array([0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A]),
  "PNG absurd chunk len":new Uint8Array([0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A, 0xFF,0xFF,0xFF,0xFF, 0x63,0x61,0x42,0x58]),
  "JPEG SOI only":       new Uint8Array([0xFF,0xD8]),
  "JPEG zero-length seg":new Uint8Array([0xFF,0xD8,0xFF,0xEB,0x00,0x00,0x4A,0x50]),
  "random bytes":        new Uint8Array(Array.from({length:512},(_,i)=>(i*37)&0xFF)),
};
for (const [name, arr] of Object.entries(cases)) {
  let r, threw = false;
  const t0 = Date.now();
  try { r = mod.parseC2PA(arr.buffer); } catch (e) { threw = true; r = e.message; }
  const ms = Date.now() - t0;
  check(`${name}: no throw, returns null, under 1s`, !threw && r === null && ms < 1000, threw ? r : `${JSON.stringify(r)} in ${ms}ms`);
}

console.log(fails ? `\n${fails} FAILED` : "\nall C2PA checks passed");
process.exit(fails ? 1 : 0);
